### ISSUE TITLE
ValueError: 'the context text' is not a valid scope name, running conversation_discriminator.py

### ISSUE THREAD

**Issue by lev-kusanagi** [oswaldoludwig/Seq2seq-Chatbot-for-Keras#12]
Error when running conversation_discriminator.py
Using Tensorflow 1.4.1, keras 2.0.4

$ python conversation_discriminator.py
Using TensorFlow backend.
Starting the model...
Traceback (most recent call last):
  File "conversation_discriminator.py", line 223, in <module>
    input_context = Input(shape=(maxlen_input,), dtype='int32', name='the context text')
  File "/home/javier/repos/dialogue/Seq2seq-Chatbot-for-Keras/venv/local/lib/python2.7/sit
e-packages/keras/engine/topology.py", line 1414, in Input                                
    input_tensor=tensor)
  File "/home/javier/repos/dialogue/Seq2seq-Chatbot-for-Keras/venv/local/lib/python2.7/sit
e-packages/keras/legacy/interfaces.py", line 88, in wrapper                              
    return func(*args, **kwargs)
  File "/home/javier/repos/dialogue/Seq2seq-Chatbot-for-Keras/venv/local/lib/python2.7/sit
e-packages/keras/engine/topology.py", line 1325, in __init__                             
    name=self.name)
  File "/home/javier/repos/dialogue/Seq2seq-Chatbot-for-Keras/venv/local/lib/python2.7/sit
e-packages/keras/backend/tensorflow_backend.py", line 391, in placeholder                
    x = tf.placeholder(dtype, shape=shape, name=name)
  File "/home/javier/repos/dialogue/Seq2seq-Chatbot-for-Keras/venv/local/lib/python2.7/sit
e-packages/tensorflow/python/ops/array_ops.py", line 1599, in placeholder                
    return gen_array_ops._placeholder(dtype=dtype, shape=shape, name=name)
  File "/home/javier/repos/dialogue/Seq2seq-Chatbot-for-Keras/venv/local/lib/python2.7/sit
e-packages/tensorflow/python/ops/gen_array_ops.py", line 3091, in _placeholder           
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/home/javier/repos/dialogue/Seq2seq-Chatbot-for-Keras/venv/local/lib/python2.7/sit
e-packages/tensorflow/python/framework/op_def_library.py", line 394, in _apply_op_helper 
    with g.as_default(), ops.name_scope(name) as scope:
  File "/home/javier/repos/dialogue/Seq2seq-Chatbot-for-Keras/venv/local/lib/python2.7/sit
e-packages/tensorflow/python/framework/ops.py", line 4932, in __enter__                  
    return self._name_scope.__enter__()
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/javier/repos/dialogue/Seq2seq-Chatbot-for-Keras/venv/local/lib/python2.7/sit
e-packages/tensorflow/python/framework/ops.py", line 3519, in name_scope                 
    raise ValueError("'%s' is not a valid scope name" % name)
ValueError: 'the context text' is not a valid scope name

**Comment by oswaldoludwig** [comment]
This project uses Theano as Backend.

**Comment by oswaldoludwig** [comment]
These links can help you: 
https://stackoverflow.com/questions/42177658/how-to-switch-backend-with-keras-from-tensorflow-to-theano
and
https://github.com/keras-team/keras/issues/5374

**Comment by muhammedmokbel** [comment]
i am facing same problem and i can't handle it 
I am working on colab so  I can't understand how to change the backend to theano ?
