### ISSUE TITLE
eroor while running conversation.py

### ISSUE THREAD

**Issue by sheenNapoleon** [oswaldoludwig/Seq2seq-Chatbot-for-Keras#24]
Traceback (most recent call last):
  File "D:\Seq2seq-Chatbot-for-Keras-master\conversation.py", line 151, in <module>
    out = Dense(dictionary_size/2, activation="relu", name='relu-activation')(merge_layer)
  File "C:\Users\sheen\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\base_layer.py", line 431, in __call__
    self.build(unpack_singleton(input_shapes))
  File "C:\Users\sheen\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\layers\core.py", line 866, in build
    constraint=self.kernel_constraint)
  File "C:\Users\sheen\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\sheen\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\base_layer.py", line 249, in add_weight
    weight = K.variable(initializer(shape),
  File "C:\Users\sheen\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\initializers.py", line 218, in __call__
    dtype=dtype, seed=self.seed)
  File "C:\Users\sheen\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\backend\tensorflow_backend.py", line 4139, in random_uniform
    dtype=dtype, seed=seed)
  File "C:\Users\sheen\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\random_ops.py", line 244, in random_uniform
    shape, dtype, seed=seed1, seed2=seed2)
  File "C:\Users\sheen\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\gen_random_ops.py", line 473, in _random_uniform
    name=name)
  File "C:\Users\sheen\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 609, in _apply_op_helper
    param_name=input_name)
  File "C:\Users\sheen\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 60, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'shape' has DataType float32 not in list of allowed values: int32, int64

**Comment by hoanganhtuanfsoft** [comment]
I think you should change backend of keras to theano. by the following solution:
import os
os.environ['KERAS_BACKEND'] = 'theano'

But I meet other issue:
Using Theano backend.
Starting the model...
Traceback (most recent call last):
  File "conversation.py", line 153, in <module>
    out = Dense(dictionary_size/2, activation="relu")(merge_layer)
  File "/home/tuanha/.virtualenvs/dl4cv/lib/python3.6/site-packages/keras/engine/base_layer.py", line 431, in __call__
    self.build(unpack_singleton(input_shapes))
  File "/home/tuanha/.virtualenvs/dl4cv/lib/python3.6/site-packages/keras/layers/core.py", line 866, in build
    constraint=self.kernel_constraint)
  File "/home/tuanha/.virtualenvs/dl4cv/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/tuanha/.virtualenvs/dl4cv/lib/python3.6/site-packages/keras/engine/base_layer.py", line 249, in add_weight
    weight = K.variable(initializer(shape),
  File "/home/tuanha/.virtualenvs/dl4cv/lib/python3.6/site-packages/keras/initializers.py", line 218, in __call__
    dtype=dtype, seed=self.seed)
  File "/home/tuanha/.virtualenvs/dl4cv/lib/python3.6/site-packages/keras/backend/theano_backend.py", line 2600, in random_uniform
    return rng.uniform(shape, low=minval, high=maxval, dtype=dtype)
  File "/home/tuanha/.virtualenvs/dl4cv/lib/python3.6/site-packages/theano/sandbox/rng_mrg.py", line 857, in uniform
    for i in size]), msg
AssertionError: size must be a tuple of int or a Theano variable
